### ISSUE TITLE
Write support for Quake III (IHV, 1.03, 1.06)?

### ISSUE THREAD

**Issue by akagemegane** [zturtleman/bsp-sekai#2]
I know some will say just play the retail Quake III Arena but I kind of wanted to put together a package of these builds for my friends containing more BSPs outside of the two maps (q3test1 and q3test2) possibly for a video project. Plus it could also fit well with backporting the levels from a mod called Lost Arena onto the IHV build just for the fun of it.

Any possibilities of implementing support for writing BSPs in IBSP 43, 44 and 45?

**Comment by zturtleman** [comment]
No, I don't have plans of further development of this software.
